# Generated by Django 5.0.10 on 2025-02-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OwnerName', models.CharField(max_length=255)),
                ('ProcessedCodeP', models.CharField(max_length=255)),
                ('tabnumber', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tabel.dbo.tabbnumber',
            },
        ),
    ]
