# Generated by Django 5.0.10 on 2025-03-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeStatus1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabnumber', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('shift', models.CharField(max_length=1)),
                ('brigade', models.CharField(max_length=1)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=255)),
            ],
        ),
    ]
