# Generated by Django 5.0.10 on 2025-02-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('schedule', models.CharField(max_length=255)),
                ('tab_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShiftSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_number', models.IntegerField()),
                ('date', models.DateField()),
                ('shift', models.CharField(max_length=255)),
                ('brigade', models.CharField(max_length=255)),
            ],
        ),
    ]
