# Generated by Django 5.0.10 on 2025-02-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_data', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeSchedule',
        ),
        migrations.RemoveField(
            model_name='shiftschedule',
            name='brigade',
        ),
        migrations.RemoveField(
            model_name='shiftschedule',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='shiftschedule',
            name='tab_number',
        ),
        migrations.AddField(
            model_name='shiftschedule',
            name='shift_1_brigade_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shiftschedule',
            name='shift_1_brigade_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shiftschedule',
            name='shift_2_brigade_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shiftschedule',
            name='shift_2_brigade_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shiftschedule',
            name='shift_2_brigade_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shiftschedule',
            name='shift_2_brigade_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shiftschedule',
            name='shift_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shiftschedule',
            name='shift_5_brigade_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shiftschedule',
            name='shift_5_brigade_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shiftschedule',
            name='shift_6',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shiftschedule',
            name='shift_7',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
