# Generated by Django 5.0.10 on 2025-03-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_data', '0002_delete_employeeschedule_remove_shiftschedule_brigade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smeny1C',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('field1', models.CharField(max_length=255)),
                ('field2', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'smeny1c',
                'managed': False,
            },
        ),
    ]
